# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acf8fea98fc6011d15d2885566e130a9ca767faa6ed1a6aee693085b8f444db00c2e8969899204f6ce3cdfab4834df9b9db5dd1d9254a93eff6905fad05cf882

test:
  secret_key_base: f12bae11e47b4d097c8f6de4b7ac24aa475ac3affa72cbe7a15f486926875d599040dc4f5bf17027d4bb793ddb4ad0004989919f41aeb10fb7469b469c0dbb2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
